stages:
  data_ingestion:
    cmd: python src/kidney_cnn_classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/kidney_cnn_classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney_ct_scan_image_normal_tumor

  
  prepare_base_model:
    cmd: python src/kidney_cnn_classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/kidney_cnn_classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/kidney_cnn_classifier/pipeline/stage_03_model_training.py
    deps:
      - src/kidney_cnn_classifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney_ct_scan_image_normal_tumor
      - artifacts/prepare_base_model
    params:
      - BATCH_SIZE
      - EPOCHS
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  

  evaluation:
    cmd: python src/kidney_cnn_classifier/pipeline/stage_04_model_evaluation_with_mlflow.py
    deps:
      - src/kidney_cnn_classifier/pipeline/stage_04_model_evaluation_with_mlflow.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney_ct_scan_image_normal_tumor
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: False
